# Airbnb Feature Selection

`airbnb_preprocessing.ipynb`에서 저장한 전처리 결과를 불러와 피처 선택 실험을 진행한다.

In [59]:
import pandas as pd
import numpy as np
from pathlib import Path

In [60]:
input_path = Path('../data/processed/airbnb_preprocessed_df.csv')
airbnb_df = pd.read_csv(input_path)

print(f'Loaded data from: {input_path.resolve()}')
print(airbnb_df.shape)

Loaded data from: /Users/junhapark/data-science-workspace/projects/airbnb-price-prediction/data/processed/airbnb_preprocessed_df.csv
(47928, 47)

In [61]:
airbnb_df.head()

,id,host_id,neighbourhood_group,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,...,misdemeanor_ratio_2km,night_crime_ratio_2km,log_minimum_nights,log_distance_to_nearest_station,log_calculated_host_listings_count,log_number_of_reviews,log_reviews_per_month,log_station_count_300m,log_station_count_500m,log_price
0,2539,2787,Brooklyn,Private room,149,1,9,0.21,6,365,...,0.515096,0.242109,0.693147,0.382104,1.945910,2.302585,0.190620,0.000000,0.693147,5.010635
1,2595,2845,Manhattan,Entire home/apt,225,1,45,0.38,2,355,...,0.540041,0.205736,0.693147,0.090684,1.098612,3.828641,0.322083,1.386294,1.945910,5.420535
2,3647,4632,Manhattan,Private room,150,3,0,0.00,1,365,...,0.578210,0.206138,1.386294,0.287966,0.693147,0.000000,0.000000,0.000000,0.693147,5.017280
3,3831,4869,Brooklyn,Entire home/apt,89,1,270,4.64,1,194,...,0.524755,0.221725,0.693147,0.347774,0.693147,5.602119,1.729884,0.000000,1.098612,4.499810
4,5022,7192,Manhattan,Entire home/apt,80,10,9,0.10,1,0,...,0.571406,0.205123,2.397895,0.182477,0.693147,2.302585,0.095310,0.693147,1.098612,4.394449

In [62]:
airbnb_df.shape

(47928, 47)

In [63]:
airbnb_df.columns

Index(['id', 'host_id', 'neighbourhood_group', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'attraction_count_2km', 'attraction_count_3km',
       'distance_to_city_center', 'is_manhattan',
       'distance_to_nearest_station', 'station_count_300m',
       'station_count_500m', 'station_count_1km', 'crime_count_0.5km',
       'crime_count_1km', 'crime_count_2km', 'felony_count_0.5km',
       'felony_count_1km', 'felony_count_2km', 'misdemeanor_count_0.5km',
       'misdemeanor_count_1km', 'misdemeanor_count_2km',
       'night_crime_count_0.5km', 'night_crime_count_1km',
       'night_crime_count_2km', 'felony_ratio_0.5km',
       'misdemeanor_ratio_0.5km', 'night_crime_ratio_0.5km',
       'felony_ratio_1km', 'misdemeanor_ratio_1km', 'night_crime_ratio_1km',
       'felony_ratio_2km', 'misdemeanor_ratio_2km', 'night_crime_ratio_2km',
       'log_minimum_nights', 'log_distance_to_nearest_station',
       'log_calculated_host_listings_count', 'log_number_of_reviews',
       'log_reviews_per_month', 'log_station_count_300m',
       'log_station_count_500m', 'log_price'],
      dtype='object')

In [64]:
null_counts = airbnb_df.isnull().sum()
null_cols = null_counts[null_counts > 0].sort_values(ascending=False)
display(null_cols)

Series([], dtype: int64)

In [65]:
# 선형회귀용 피처 선택 시작용 복사본
linear_df = airbnb_df.copy()

# 공통 제외 컬럼
drop_cols = ['id', 'host_id', 'price']
drop_cols = [col for col in drop_cols if col in linear_df.columns]

linear_df = linear_df.drop(columns=drop_cols)

print(linear_df.columns.tolist())
print(linear_df.shape)

['neighbourhood_group', 'room_type', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'attraction_count_2km', 'attraction_count_3km', 'distance_to_city_center', 'is_manhattan', 'distance_to_nearest_station', 'station_count_300m', 'station_count_500m', 'station_count_1km', 'crime_count_0.5km', 'crime_count_1km', 'crime_count_2km', 'felony_count_0.5km', 'felony_count_1km', 'felony_count_2km', 'misdemeanor_count_0.5km', 'misdemeanor_count_1km', 'misdemeanor_count_2km', 'night_crime_count_0.5km', 'night_crime_count_1km', 'night_crime_count_2km', 'felony_ratio_0.5km', 'misdemeanor_ratio_0.5km', 'night_crime_ratio_0.5km', 'felony_ratio_1km', 'misdemeanor_ratio_1km', 'night_crime_ratio_1km', 'felony_ratio_2km', 'misdemeanor_ratio_2km', 'night_crime_ratio_2km', 'log_minimum_nights', 'log_distance_to_nearest_station', 'log_calculated_host_listings_count', 'log_number_of_reviews', 'log_reviews_per_month', 'log_station_count_300m', 'log_station_count_500m', 'log_price']
(47928, 44)

In [66]:
categorical_cols = ['neighbourhood_group', 'room_type']
categorical_cols = [col for col in categorical_cols if col in linear_df.columns]

linear_df = pd.get_dummies(
    linear_df,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

print(linear_df.columns.tolist())
print(linear_df.shape)

['minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'attraction_count_2km', 'attraction_count_3km', 'distance_to_city_center', 'is_manhattan', 'distance_to_nearest_station', 'station_count_300m', 'station_count_500m', 'station_count_1km', 'crime_count_0.5km', 'crime_count_1km', 'crime_count_2km', 'felony_count_0.5km', 'felony_count_1km', 'felony_count_2km', 'misdemeanor_count_0.5km', 'misdemeanor_count_1km', 'misdemeanor_count_2km', 'night_crime_count_0.5km', 'night_crime_count_1km', 'night_crime_count_2km', 'felony_ratio_0.5km', 'misdemeanor_ratio_0.5km', 'night_crime_ratio_0.5km', 'felony_ratio_1km', 'misdemeanor_ratio_1km', 'night_crime_ratio_1km', 'felony_ratio_2km', 'misdemeanor_ratio_2km', 'night_crime_ratio_2km', 'log_minimum_nights', 'log_distance_to_nearest_station', 'log_calculated_host_listings_count', 'log_number_of_reviews', 'log_reviews_per_month', 'log_station_count_300m', 'log_station_count_500m', 'log_price', 'neighbourhood_group_Brooklyn', 'neighbourhood_group_Manhattan', 'neighbourhood_group_Queens', 'neighbourhood_group_Staten Island', 'room_type_Private room', 'room_type_Shared room']
(47928, 48)

In [67]:
log_cols = [col for col in airbnb_df.columns if col.startswith('log_')]
airbnb_df[log_cols].head()

,log_minimum_nights,log_distance_to_nearest_station,log_calculated_host_listings_count,log_number_of_reviews,log_reviews_per_month,log_station_count_300m,log_station_count_500m,log_price
0,0.693147,0.382104,1.945910,2.302585,0.190620,0.000000,0.693147,5.010635
1,0.693147,0.090684,1.098612,3.828641,0.322083,1.386294,1.945910,5.420535
2,1.386294,0.287966,0.693147,0.000000,0.000000,0.000000,0.693147,5.017280
3,0.693147,0.347774,0.693147,5.602119,1.729884,0.000000,1.098612,4.499810
4,2.397895,0.182477,0.693147,2.302585,0.095310,0.693147,1.098612,4.394449

In [45]:
feature_cols = [col for col in linear_df.columns if col != 'log_price']

corr_with_target = (
    linear_df[feature_cols + ['log_price']]
    .corr(numeric_only=True)['log_price']
    .drop('log_price')
    .sort_values(key=lambda s: s.abs(), ascending=False)
)

corr_rank_df = pd.DataFrame({
    'feature': corr_with_target.index,
    'corr_with_log_price': corr_with_target.values
})

display(corr_rank_df)

                               feature  corr_with_log_price
0               room_type_Private room            -0.589818
1                 attraction_count_3km             0.467104
2                 attraction_count_2km             0.424469
3              distance_to_city_center            -0.400677
4        neighbourhood_group_Manhattan             0.354190
5                         is_manhattan             0.354190
6                night_crime_ratio_2km            -0.326212
7                    station_count_1km             0.315935
8                     felony_count_2km             0.281844
9                     felony_count_1km             0.281699
10                  felony_count_0.5km             0.269017
11               misdemeanor_count_2km             0.267779
12               misdemeanor_count_1km             0.266185
13                     crime_count_1km             0.258958
14                     crime_count_2km             0.255203
15             misdemeanor_count_0.5km             0.251909
16                   crime_count_0.5km             0.248668
17                  station_count_500m             0.235249
18               misdemeanor_ratio_2km             0.229122
19               night_crime_ratio_1km            -0.217997
20               night_crime_count_1km             0.215706
21             night_crime_count_0.5km             0.212531
22              log_station_count_500m             0.206117
23               night_crime_count_2km             0.197328
24        neighbourhood_group_Brooklyn            -0.192530
25          neighbourhood_group_Queens            -0.188834
26               room_type_Shared room            -0.182071
27               misdemeanor_ratio_1km             0.170587
28                  station_count_300m             0.159892
29                    felony_ratio_2km             0.153003
30      calculated_host_listings_count             0.146281
31              log_station_count_300m             0.136546
32             misdemeanor_ratio_0.5km             0.124261
33             night_crime_ratio_0.5km            -0.121078
34     log_distance_to_nearest_station            -0.120897
35                    felony_ratio_1km             0.115935
36         distance_to_nearest_station            -0.095798
37                  felony_ratio_0.5km             0.092302
38                    availability_365             0.086515
39                  log_minimum_nights             0.070443
40  log_calculated_host_listings_count             0.056055
41                   reviews_per_month            -0.050815
42               log_number_of_reviews            -0.050326
43                      minimum_nights             0.049865
44   neighbourhood_group_Staten Island            -0.048809
45               log_reviews_per_month            -0.048095
46                   number_of_reviews            -0.033697

In [68]:
selected_derived_features = [
    'night_crime_ratio_2km',
    'misdemeanor_ratio_2km',
    'felony_count_2km',
    'attraction_count_3km',
    'distance_to_city_center',
    'is_manhattan',
    'log_distance_to_nearest_station',
    'station_count_1km'
]

In [69]:
selected_derived_features = [
    'night_crime_ratio_2km',
    'misdemeanor_ratio_2km',
    'felony_count_2km',
    'attraction_count_3km',
    'distance_to_city_center',
    'is_manhattan',
    'log_distance_to_nearest_station',
    'station_count_1km'
]

derived_feature_candidates = [
    'attraction_count_2km', 'attraction_count_3km',
    'distance_to_city_center', 'is_manhattan',
    'distance_to_nearest_station', 'log_distance_to_nearest_station',
    'station_count_300m', 'station_count_500m', 'station_count_1km',
    'log_station_count_300m', 'log_station_count_500m',
    'crime_count_0.5km', 'crime_count_1km', 'crime_count_2km',
    'felony_count_0.5km', 'felony_count_1km', 'felony_count_2km',
    'misdemeanor_count_0.5km', 'misdemeanor_count_1km', 'misdemeanor_count_2km',
    'night_crime_count_0.5km', 'night_crime_count_1km', 'night_crime_count_2km',
    'felony_ratio_0.5km', 'felony_ratio_1km', 'felony_ratio_2km',
    'misdemeanor_ratio_0.5km', 'misdemeanor_ratio_1km', 'misdemeanor_ratio_2km',
    'night_crime_ratio_0.5km', 'night_crime_ratio_1km', 'night_crime_ratio_2km'
]

drop_derived_features = [
    col for col in derived_feature_candidates
    if col in linear_df.columns and col not in selected_derived_features
]

linear_df = linear_df.drop(columns=drop_derived_features)

print("drop된 파생변수:", drop_derived_features)
print("남은 선택 파생변수:", [col for col in selected_derived_features if col in linear_df.columns])

drop된 파생변수: ['attraction_count_2km', 'distance_to_nearest_station', 'station_count_300m', 'station_count_500m', 'log_station_count_300m', 'log_station_count_500m', 'crime_count_0.5km', 'crime_count_1km', 'crime_count_2km', 'felony_count_0.5km', 'felony_count_1km', 'misdemeanor_count_0.5km', 'misdemeanor_count_1km', 'misdemeanor_count_2km', 'night_crime_count_0.5km', 'night_crime_count_1km', 'night_crime_count_2km', 'felony_ratio_0.5km', 'felony_ratio_1km', 'felony_ratio_2km', 'misdemeanor_ratio_0.5km', 'misdemeanor_ratio_1km', 'night_crime_ratio_0.5km', 'night_crime_ratio_1km']
남은 선택 파생변수: ['night_crime_ratio_2km', 'misdemeanor_ratio_2km', 'felony_count_2km', 'attraction_count_3km', 'distance_to_city_center', 'is_manhattan', 'log_distance_to_nearest_station', 'station_count_1km']

In [70]:
linear_df.shape

(47928, 24)

In [71]:
feature_cols = [col for col in linear_df.columns if col != 'log_price']

corr_with_target = (
    linear_df[feature_cols + ['log_price']]
    .corr(numeric_only=True)['log_price']
    .drop('log_price')
    .sort_values(key=lambda s: s.abs(), ascending=False)
)

corr_rank_df = pd.DataFrame({
    'feature': corr_with_target.index,
    'corr_with_log_price': corr_with_target.values
})

display(corr_rank_df)

                               feature  corr_with_log_price
0               room_type_Private room            -0.589818
1                 attraction_count_3km             0.467104
2              distance_to_city_center            -0.400677
3        neighbourhood_group_Manhattan             0.354190
4                         is_manhattan             0.354190
5                night_crime_ratio_2km            -0.326212
6                    station_count_1km             0.315935
7                     felony_count_2km             0.281844
8                misdemeanor_ratio_2km             0.229122
9         neighbourhood_group_Brooklyn            -0.192530
10          neighbourhood_group_Queens            -0.188834
11               room_type_Shared room            -0.182071
12      calculated_host_listings_count             0.146281
13     log_distance_to_nearest_station            -0.120897
14                    availability_365             0.086515
15                  log_minimum_nights             0.070443
16  log_calculated_host_listings_count             0.056055
17                   reviews_per_month            -0.050815
18               log_number_of_reviews            -0.050326
19                      minimum_nights             0.049865
20   neighbourhood_group_Staten Island            -0.048809
21               log_reviews_per_month            -0.048095
22                   number_of_reviews            -0.033697

In [72]:
# 1. 완전/강한 중복 변수 제거
cols_to_drop = [
    'is_manhattan',  # neighbourhood_group_Manhattan과 중복
    'minimum_nights', # log 변환본으로 선택
    'calculated_host_listings_count',  # log 변환본으로 선택
    'number_of_reviews',  # log 변환본으로 선택
    'reviews_per_month'  # log 변환본으로 선택
]

cols_to_drop = [col for col in cols_to_drop if col in linear_df.columns]
linear_df = linear_df.drop(columns=cols_to_drop)

print("drop된 컬럼:", cols_to_drop)
print("\n남은 컬럼:")
print(linear_df.columns.tolist())

drop된 컬럼: ['is_manhattan', 'minimum_nights', 'calculated_host_listings_count', 'number_of_reviews', 'reviews_per_month']

남은 컬럼:
['availability_365', 'attraction_count_3km', 'distance_to_city_center', 'station_count_1km', 'felony_count_2km', 'misdemeanor_ratio_2km', 'night_crime_ratio_2km', 'log_minimum_nights', 'log_distance_to_nearest_station', 'log_calculated_host_listings_count', 'log_number_of_reviews', 'log_reviews_per_month', 'log_price', 'neighbourhood_group_Brooklyn', 'neighbourhood_group_Manhattan', 'neighbourhood_group_Queens', 'neighbourhood_group_Staten Island', 'room_type_Private room', 'room_type_Shared room']

In [73]:
feature_cols = [col for col in linear_df.columns if col != 'log_price']

corr_with_target = (
    linear_df[feature_cols + ['log_price']]
    .corr(numeric_only=True)['log_price']
    .drop('log_price')
    .sort_values(key=lambda s: s.abs(), ascending=False)
)

corr_rank_df = pd.DataFrame({
    'feature': corr_with_target.index,
    'corr_with_log_price': corr_with_target.values
})

display(corr_rank_df)

                               feature  corr_with_log_price
0               room_type_Private room            -0.589818
1                 attraction_count_3km             0.467104
2              distance_to_city_center            -0.400677
3        neighbourhood_group_Manhattan             0.354190
4                night_crime_ratio_2km            -0.326212
5                    station_count_1km             0.315935
6                     felony_count_2km             0.281844
7                misdemeanor_ratio_2km             0.229122
8         neighbourhood_group_Brooklyn            -0.192530
9           neighbourhood_group_Queens            -0.188834
10               room_type_Shared room            -0.182071
11     log_distance_to_nearest_station            -0.120897
12                    availability_365             0.086515
13                  log_minimum_nights             0.070443
14  log_calculated_host_listings_count             0.056055
15               log_number_of_reviews            -0.050326
16   neighbourhood_group_Staten Island            -0.048809
17               log_reviews_per_month            -0.048095

In [74]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor

# log_price 제외한 현재 후보 피처 전체
feature_cols = [col for col in linear_df.columns if col != 'log_price']

multicol_df = linear_df[feature_cols].copy()
multicol_df = multicol_df.replace([np.inf, -np.inf], np.nan).dropna()

# 1. 상관행렬
corr_matrix = multicol_df.corr(numeric_only=True).round(4)
display(corr_matrix)

# 2. VIF 계산
multicol_df_const = sm.add_constant(multicol_df)

vif_df = pd.DataFrame({
    'feature': multicol_df_const.columns,
    'VIF': [
        variance_inflation_factor(multicol_df_const.values, i)
        for i in range(multicol_df_const.shape[1])
    ]
})

vif_df = vif_df[vif_df['feature'] != 'const'].sort_values('VIF', ascending=False)
display(vif_df)

# 3. 각 변수를 나머지 변수들로 회귀한 R² / implied VIF
r2_rows = []

for target_feature in feature_cols:
    other_features = [col for col in feature_cols if col != target_feature]

    X = multicol_df[other_features]
    y = multicol_df[target_feature]

    model = LinearRegression()
    model.fit(X, y)

    r2 = model.score(X, y)
    implied_vif = 1 / (1 - r2) if r2 < 1 else np.inf

    r2_rows.append({
        'target_feature': target_feature,
        'R_squared': r2,
        'implied_vif': implied_vif
    })

r2_df = pd.DataFrame(r2_rows).sort_values('implied_vif', ascending=False)
display(r2_df)

,availability_365,attraction_count_3km,distance_to_city_center,station_count_1km,felony_count_2km,misdemeanor_ratio_2km,night_crime_ratio_2km,log_minimum_nights,log_distance_to_nearest_station,log_calculated_host_listings_count,log_number_of_reviews,log_reviews_per_month,neighbourhood_group_Brooklyn,neighbourhood_group_Manhattan,neighbourhood_group_Queens,neighbourhood_group_Staten Island,room_type_Private room,room_type_Shared room
availability_365,1.0000,0.0162,0.0927,-0.0152,-0.0218,-0.0141,0.0005,0.1734,0.1140,0.4046,0.1796,0.2060,-0.0770,-0.0112,0.0907,0.0584,-0.0068,0.0603
attraction_count_3km,0.0162,1.0000,-0.6932,0.6020,0.6829,0.4199,-0.5123,0.1383,-0.1807,0.1800,-0.0909,-0.0780,-0.5113,0.7314,-0.2757,-0.0688,-0.2370,-0.0104
distance_to_city_center,0.0927,-0.6932,1.0000,-0.4427,-0.5962,-0.3660,0.3547,-0.1551,0.4407,-0.0978,0.0995,0.1288,0.3369,-0.6177,0.2737,0.2436,0.1665,0.0288
station_count_1km,-0.0152,0.6020,-0.4427,1.0000,0.5030,0.3564,-0.3501,0.0929,-0.4209,0.1650,-0.0778,-0.0684,-0.2429,0.4621,-0.2677,-0.1110,-0.1308,-0.0321
felony_count_2km,-0.0218,0.6829,-0.5962,0.5030,1.0000,0.2707,-0.4218,0.0851,-0.3423,0.0697,-0.0347,-0.0393,-0.2725,0.6063,-0.4589,-0.1579,-0.1092,-0.0124
misdemeanor_ratio_2km,-0.0141,0.4199,-0.3660,0.3564,0.2707,1.0000,-0.4223,0.0537,-0.2015,0.0749,-0.0347,-0.0462,-0.6509,0.6932,-0.1258,-0.0045,-0.1113,0.0110
night_crime_ratio_2km,0.0005,-0.5123,0.3547,-0.3501,-0.4218,-0.4223,1.0000,-0.1104,0.1025,-0.1187,0.0444,0.0656,0.2226,-0.5414,0.4787,-0.0009,0.1855,0.0193
log_minimum_nights,0.1734,0.1383,-0.1551,0.0929,0.0851,0.0537,-0.1104,1.0000,-0.0708,0.3759,-0.2213,-0.2944,-0.0400,0.1117,-0.0815,-0.0225,-0.1718,-0.0428
log_distance_to_nearest_station,0.1140,-0.1807,0.4407,-0.4209,-0.3423,-0.2015,0.1025,-0.0708,1.0000,-0.0025,0.0611,0.1106,-0.0752,-0.2237,0.2918,0.5328,0.0396,0.0048
log_calculated_host_listings_count,0.4046,0.1800,-0.0978,0.1650,0.0697,0.0749,-0.1187,0.3759,-0.0025,1.0000,-0.0977,-0.0341,-0.1311,0.1245,0.0142,-0.0012,-0.0222,0.0558
log_number_of_reviews,0.1796,-0.0909,0.0995,-0.0778,-0.0347,-0.0347,0.0444,-0.2213,0.0611,-0.0977,1.0000,0.7601,0.0332,-0.0696,0.0401,0.0258,-0.0025,-0.0275
log_reviews_per_month,0.2060,-0.0780,0.1288,-0.0684,-0.0393,-0.0462,0.0656,-0.2944,0.1106,-0.0341,0.7601,1.0000,-0.0107,-0.0726,0.0984,0.0347,0.0191,-0.0002
neighbourhood_group_Brooklyn,-0.0770,-0.5113,0.3369,-0.2429,-0.2725,-0.6509,0.2226,-0.0400,-0.0752,-0.1311,0.0332,-0.0107,1.0000,-0.7430,-0.3060,-0.0739,0.0765,-0.0170
neighbourhood_group_Manhattan,-0.0112,0.7314,-0.6177,0.4621,0.6063,0.6932,-0.5414,0.1117,-0.2237,0.1245,-0.0696,-0.0726,-0.7430,1.0000,-0.3224,-0.0778,-0.1545,-0.0086
neighbourhood_group_Queens,0.0907,-0.2757,0.2737,-0.2677,-0.4589,-0.1258,0.4787,-0.0815,0.2918,0.0142,0.0401,0.0984,-0.3060,-0.3224,1.0000,-0.0321,0.0990,0.0253
neighbourhood_group_Staten Island,0.0584,-0.0688,0.2436,-0.1110,-0.1579,-0.0045,-0.0009,-0.0225,0.5328,-0.0012,0.0258,0.0347,-0.0739,-0.0778,-0.0321,1.0000,0.0088,0.0004
room_type_Private room,-0.0068,-0.2370,0.1665,-0.1308,-0.1092,-0.1113,0.1855,-0.1718,0.0396,-0.0222,-0.0025,0.0191,0.0765,-0.1545,0.0990,0.0088,1.0000,-0.1442
room_type_Shared room,0.0603,-0.0104,0.0288,-0.0321,-0.0124,0.0110,0.0193,-0.0428,0.0048,0.0558,-0.0275,-0.0002,-0.0170,-0.0086,0.0253,0.0004,-0.1442,1.0000

                               feature        VIF
14       neighbourhood_group_Manhattan  14.072866
13        neighbourhood_group_Brooklyn  13.964351
15          neighbourhood_group_Queens   6.581652
2                 attraction_count_3km   4.379806
3              distance_to_city_center   2.747593
6                misdemeanor_ratio_2km   2.694614
5                     felony_count_2km   2.610374
12               log_reviews_per_month   2.593728
11               log_number_of_reviews   2.453607
9      log_distance_to_nearest_station   2.369884
4                    station_count_1km   2.050959
7                night_crime_ratio_2km   1.876245
16   neighbourhood_group_Staten Island   1.810697
10  log_calculated_host_listings_count   1.453162
8                   log_minimum_nights   1.373656
1                     availability_365   1.338081
17              room_type_Private room   1.145806
18               room_type_Shared room   1.047395

                        target_feature  R_squared  implied_vif
13       neighbourhood_group_Manhattan   0.928941    14.072866
12        neighbourhood_group_Brooklyn   0.928389    13.964351
14          neighbourhood_group_Queens   0.848062     6.581652
1                 attraction_count_3km   0.771679     4.379806
2              distance_to_city_center   0.636045     2.747593
5                misdemeanor_ratio_2km   0.628889     2.694614
4                     felony_count_2km   0.616913     2.610374
11               log_reviews_per_month   0.614455     2.593728
10               log_number_of_reviews   0.592437     2.453607
8      log_distance_to_nearest_station   0.578038     2.369884
3                    station_count_1km   0.512423     2.050959
6                night_crime_ratio_2km   0.467020     1.876245
15   neighbourhood_group_Staten Island   0.447727     1.810697
9   log_calculated_host_listings_count   0.311845     1.453162
7                   log_minimum_nights   0.272016     1.373656
0                     availability_365   0.252661     1.338081
16              room_type_Private room   0.127252     1.145806
17               room_type_Shared room   0.045251     1.047395

In [76]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor

feature_groups = {
    'location': [
        'attraction_count_3km',
        'distance_to_city_center',
        'neighbourhood_group_Manhattan'
    ],
    'crime': [
        'night_crime_ratio_2km',
        'felony_count_2km',
        'misdemeanor_ratio_2km'
    ],
    'station': [
        'station_count_1km',
        'log_distance_to_nearest_station'
    ],
    'room_type': [
        'room_type_Private room',
        'room_type_Shared room'
    ]
}

for group_name, features in feature_groups.items():
    valid_features = [col for col in features if col in linear_df.columns]
    group_df = linear_df[valid_features].copy()
    group_df = group_df.replace([np.inf, -np.inf], np.nan).dropna()

    print(f"\n===== {group_name.upper()} =====")

    # 1. 그룹 내부 상관계수
    print("\n[Correlation Matrix]")
    display(group_df.corr(numeric_only=True).round(4))

    # 2. 절편 포함 VIF
    print("\n[VIF]")
    group_df_const = sm.add_constant(group_df)

    vif_df = pd.DataFrame({
        'feature': group_df_const.columns,
        'VIF': [
            variance_inflation_factor(group_df_const.values, i)
            for i in range(group_df_const.shape[1])
        ]
    })

    vif_df = vif_df[vif_df['feature'] != 'const'].sort_values('VIF', ascending=False)
    display(vif_df)

    # 3. 각 변수를 나머지 변수들로 회귀했을 때 R² / implied VIF
    print("\n[R^2 and Implied VIF]")
    r2_rows = []

    for target_feature in valid_features:
        other_features = [col for col in valid_features if col != target_feature]

        if len(other_features) == 0:
            continue

        X = group_df[other_features]
        y = group_df[target_feature]

        model = LinearRegression()
        model.fit(X, y)

        r2 = model.score(X, y)
        implied_vif = 1 / (1 - r2) if r2 < 1 else np.inf

        r2_rows.append({
            'target_feature': target_feature,
            'R_squared': r2,
            'implied_vif': implied_vif
        })

    if r2_rows:
        r2_df = pd.DataFrame(r2_rows).sort_values('implied_vif', ascending=False)
        display(r2_df)

===== LOCATION =====

[Correlation Matrix]

,attraction_count_3km,distance_to_city_center,neighbourhood_group_Manhattan
attraction_count_3km,1.0000,-0.6932,0.7314
distance_to_city_center,-0.6932,1.0000,-0.6177
neighbourhood_group_Manhattan,0.7314,-0.6177,1.0000

[VIF]

                         feature       VIF
1           attraction_count_3km  2.696837
3  neighbourhood_group_Manhattan  2.265120
2        distance_to_city_center  2.027725

[R^2 and Implied VIF]

                  target_feature  R_squared  implied_vif
0           attraction_count_3km   0.629195     2.696837
2  neighbourhood_group_Manhattan   0.558522     2.265120
1        distance_to_city_center   0.506836     2.027725

===== CRIME =====

[Correlation Matrix]

,night_crime_ratio_2km,felony_count_2km,misdemeanor_ratio_2km
night_crime_ratio_2km,1.0000,-0.4218,-0.4223
felony_count_2km,-0.4218,1.0000,0.2707
misdemeanor_ratio_2km,-0.4223,0.2707,1.0000

[VIF]

                 feature       VIF
1  night_crime_ratio_2km  1.389689
3  misdemeanor_ratio_2km  1.232742
2       felony_count_2km  1.232110

[R^2 and Implied VIF]

          target_feature  R_squared  implied_vif
0  night_crime_ratio_2km   0.280414     1.389689
2  misdemeanor_ratio_2km   0.188800     1.232742
1       felony_count_2km   0.188384     1.232110

===== STATION =====

[Correlation Matrix]

,station_count_1km,log_distance_to_nearest_station
station_count_1km,1.0000,-0.4209
log_distance_to_nearest_station,-0.4209,1.0000

[VIF]

                           feature     VIF
2  log_distance_to_nearest_station  1.2153
1                station_count_1km  1.2153

[R^2 and Implied VIF]

                    target_feature  R_squared  implied_vif
1  log_distance_to_nearest_station   0.177158       1.2153
0                station_count_1km   0.177158       1.2153

===== ROOM_TYPE =====

[Correlation Matrix]

                        room_type_Private room  room_type_Shared room
room_type_Private room                  1.0000                -0.1442
room_type_Shared room                  -0.1442                 1.0000

[VIF]

                  feature      VIF
2   room_type_Shared room  1.02124
1  room_type_Private room  1.02124

[R^2 and Implied VIF]

           target_feature  R_squared  implied_vif
1   room_type_Shared room   0.020798      1.02124
0  room_type_Private room   0.020798      1.02124

In [53]:
final_linear_features = [
    feature
    for features in feature_groups.values()
    for feature in features
]

print(final_linear_features)

['attraction_count_3km', 'distance_to_city_center', 'neighbourhood_group_Manhattan', 'night_crime_ratio_2km', 'felony_count_2km', 'misdemeanor_ratio_2km', 'station_count_1km', 'log_distance_to_nearest_station', 'room_type_Private room', 'room_type_Shared room']

In [54]:
from pathlib import Path

final_linear_features = [
    'attraction_count_3km',
    'distance_to_city_center',
    'neighbourhood_group_Manhattan',
    'night_crime_ratio_2km',
    'felony_count_2km',
    'misdemeanor_ratio_2km',
    'station_count_1km',
    'log_distance_to_nearest_station',
    'room_type_Private room',
    'room_type_Shared room'
]

linear_model_df = linear_df[final_linear_features + ['log_price']].copy()

output_path = Path('../data/processed/airbnb_linear_features_df.csv')
linear_model_df.to_csv(output_path, index=False)

print(f"saved to: {output_path}")
print(linear_model_df.shape)
linear_model_df.head()

saved to: ../data/processed/airbnb_linear_features_df.csv
(47928, 11)

,attraction_count_3km,distance_to_city_center,neighbourhood_group_Manhattan,night_crime_ratio_2km,felony_count_2km,misdemeanor_ratio_2km,station_count_1km,log_distance_to_nearest_station,room_type_Private room,room_type_Shared room,log_price
0,2,12.337898,0,0.242109,2899,0.515096,4,0.382104,1,0,5.010635
1,19,0.508366,1,0.205736,10974,0.540041,18,0.090684,0,0,5.420535
2,1,6.757240,1,0.206138,8335,0.578210,4,0.287966,1,0,5.017280
3,2,8.387034,0,0.221725,5417,0.524755,7,0.347774,0,0,4.499810
4,2,5.701496,1,0.205123,7054,0.571406,6,0.182477,0,0,4.394449

In [58]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from statsmodels.stats.outliers_influence import variance_inflation_factor

final_linear_features = [
    'attraction_count_3km',
    'distance_to_city_center',
    'neighbourhood_group_Manhattan',
    'night_crime_ratio_2km',
    'felony_count_2km',
    'misdemeanor_ratio_2km',
    'station_count_1km',
    'log_distance_to_nearest_station',
    'room_type_Private room',
    'room_type_Shared room'
]

final_df = linear_df[final_linear_features].copy()
final_df = final_df.replace([np.inf, -np.inf], np.nan).dropna()

# 1. 상관행렬
corr_matrix = final_df.corr(numeric_only=True).round(4)
display(corr_matrix)

# 2. VIF
final_df_const = sm.add_constant(final_df)

vif_df = pd.DataFrame({
    'feature': final_df_const.columns,
    'VIF': [
        variance_inflation_factor(final_df_const.values, i)
        for i in range(final_df_const.shape[1])
    ]
})

vif_df = vif_df[vif_df['feature'] != 'const'].sort_values('VIF', ascending=False)
display(vif_df)

# 3. 각 변수를 나머지 변수로 회귀한 R² / implied VIF
r2_rows = []

for target_feature in final_linear_features:
    other_features = [col for col in final_linear_features if col != target_feature]

    X = final_df[other_features]
    y = final_df[target_feature]

    model = LinearRegression()
    model.fit(X, y)

    r2 = model.score(X, y)
    implied_vif = 1 / (1 - r2) if r2 < 1 else np.inf

    r2_rows.append({
        'target_feature': target_feature,
        'R_squared': r2,
        'implied_vif': implied_vif
    })

r2_df = pd.DataFrame(r2_rows).sort_values('implied_vif', ascending=False)
display(r2_df)

,attraction_count_3km,distance_to_city_center,neighbourhood_group_Manhattan,night_crime_ratio_2km,felony_count_2km,misdemeanor_ratio_2km,station_count_1km,log_distance_to_nearest_station,room_type_Private room,room_type_Shared room
attraction_count_3km,1.0000,-0.6932,0.7314,-0.5123,0.6829,0.4199,0.6020,-0.1807,-0.2370,-0.0104
distance_to_city_center,-0.6932,1.0000,-0.6177,0.3547,-0.5962,-0.3660,-0.4427,0.4407,0.1665,0.0288
neighbourhood_group_Manhattan,0.7314,-0.6177,1.0000,-0.5414,0.6063,0.6932,0.4621,-0.2237,-0.1545,-0.0086
night_crime_ratio_2km,-0.5123,0.3547,-0.5414,1.0000,-0.4218,-0.4223,-0.3501,0.1025,0.1855,0.0193
felony_count_2km,0.6829,-0.5962,0.6063,-0.4218,1.0000,0.2707,0.5030,-0.3423,-0.1092,-0.0124
misdemeanor_ratio_2km,0.4199,-0.3660,0.6932,-0.4223,0.2707,1.0000,0.3564,-0.2015,-0.1113,0.0110
station_count_1km,0.6020,-0.4427,0.4621,-0.3501,0.5030,0.3564,1.0000,-0.4209,-0.1308,-0.0321
log_distance_to_nearest_station,-0.1807,0.4407,-0.2237,0.1025,-0.3423,-0.2015,-0.4209,1.0000,0.0396,0.0048
room_type_Private room,-0.2370,0.1665,-0.1545,0.1855,-0.1092,-0.1113,-0.1308,0.0396,1.0000,-0.1442
room_type_Shared room,-0.0104,0.0288,-0.0086,0.0193,-0.0124,0.0110,-0.0321,0.0048,-0.1442,1.0000

                            feature       VIF
1              attraction_count_3km  4.199070
3     neighbourhood_group_Manhattan  4.077113
2           distance_to_city_center  2.589842
5                  felony_count_2km  2.332652
6             misdemeanor_ratio_2km  2.207979
7                 station_count_1km  1.966052
8   log_distance_to_nearest_station  1.640557
4             night_crime_ratio_2km  1.536705
9            room_type_Private room  1.102463
10            room_type_Shared room  1.028013

                    target_feature  R_squared  implied_vif
0             attraction_count_3km   0.761852     4.199070
2    neighbourhood_group_Manhattan   0.754728     4.077113
1          distance_to_city_center   0.613876     2.589842
4                 felony_count_2km   0.571303     2.332652
5            misdemeanor_ratio_2km   0.547097     2.207979
6                station_count_1km   0.491367     1.966052
7  log_distance_to_nearest_station   0.390451     1.640557
3            night_crime_ratio_2km   0.349257     1.536705
8           room_type_Private room   0.092940     1.102463
9            room_type_Shared room   0.027250     1.028013

## tree_df

In [55]:
import pandas as pd

tree_df = pd.read_csv('../data/processed/airbnb_preprocessed_df.csv')
print(tree_df.shape)
tree_df.head()

(47928, 47)

,id,host_id,neighbourhood_group,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,...,misdemeanor_ratio_2km,night_crime_ratio_2km,log_minimum_nights,log_distance_to_nearest_station,log_calculated_host_listings_count,log_number_of_reviews,log_reviews_per_month,log_station_count_300m,log_station_count_500m,log_price
0,2539,2787,Brooklyn,Private room,149,1,9,0.21,6,365,...,0.515096,0.242109,0.693147,0.382104,1.945910,2.302585,0.190620,0.000000,0.693147,5.010635
1,2595,2845,Manhattan,Entire home/apt,225,1,45,0.38,2,355,...,0.540041,0.205736,0.693147,0.090684,1.098612,3.828641,0.322083,1.386294,1.945910,5.420535
2,3647,4632,Manhattan,Private room,150,3,0,0.00,1,365,...,0.578210,0.206138,1.386294,0.287966,0.693147,0.000000,0.000000,0.000000,0.693147,5.017280
3,3831,4869,Brooklyn,Entire home/apt,89,1,270,4.64,1,194,...,0.524755,0.221725,0.693147,0.347774,0.693147,5.602119,1.729884,0.000000,1.098612,4.499810
4,5022,7192,Manhattan,Entire home/apt,80,10,9,0.10,1,0,...,0.571406,0.205123,2.397895,0.182477,0.693147,2.302585,0.095310,0.693147,1.098612,4.394449

In [56]:
tree_df = airbnb_df.copy()

# id, host_id 제거
drop_cols = ['id', 'host_id']
drop_cols = [col for col in drop_cols if col in tree_df.columns]

tree_df = tree_df.drop(columns=drop_cols)

# log_price를 제외한 log 컬럼 제거
log_cols_to_drop = [
    col for col in tree_df.columns
    if col.startswith('log_') and col != 'log_price'
]

tree_df = tree_df.drop(columns=log_cols_to_drop)

print(tree_df.columns.tolist())
print(tree_df.shape)

['neighbourhood_group', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'attraction_count_2km', 'attraction_count_3km', 'distance_to_city_center', 'is_manhattan', 'distance_to_nearest_station', 'station_count_300m', 'station_count_500m', 'station_count_1km', 'crime_count_0.5km', 'crime_count_1km', 'crime_count_2km', 'felony_count_0.5km', 'felony_count_1km', 'felony_count_2km', 'misdemeanor_count_0.5km', 'misdemeanor_count_1km', 'misdemeanor_count_2km', 'night_crime_count_0.5km', 'night_crime_count_1km', 'night_crime_count_2km', 'felony_ratio_0.5km', 'misdemeanor_ratio_0.5km', 'night_crime_ratio_0.5km', 'felony_ratio_1km', 'misdemeanor_ratio_1km', 'night_crime_ratio_1km', 'felony_ratio_2km', 'misdemeanor_ratio_2km', 'night_crime_ratio_2km', 'log_price']
(47928, 38)

In [57]:

from pathlib import Path

output_path = Path('../data/processed/airbnb_tree_features_df.csv')
tree_df.to_csv(output_path, index=False)

print(f"saved to: {output_path}")
print(tree_df.shape)

saved to: ../data/processed/airbnb_tree_features_df.csv
(47928, 38)